
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

security:
  jwt:
    secret-key: ${SECRET_KEY:default_dev_secret_key}
authEnabled : true


logging:
  level:
    root: INFO
    com.yourpackage: DEBUG
    com.zaxxer.hikari.pool.HikariPool: WARN
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

  file:
    name: logs/app.log
    max-size: 10MB
    max-history: 7

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7




app:
  search-radius-km: 20
  default-user-id: 123e4567-e89b-12d3-a456-426614174000





# logging

